    general {
        layout = dwindle
    }
    
    # Restore Normal Movement
    bind = SUPER, left, movefocus, l
    bind = SUPER, right, movefocus, r
    bind = SUPER, up, movefocus, u
    bind = SUPER, down, movefocus, d
    
    bind = SUPER SHIFT, left, swapwindow, l
    bind = SUPER SHIFT, right, swapwindow, r
    bind = SUPER SHIFT, up, swapwindow, u
    bind = SUPER SHIFT, down, swapwindow, d

    # Restore Grouping Keys
    bind = SUPER, G, togglegroup
    bind = SUPER SHIFT, G, moveoutofgroup
    bind = SUPER CTRL, left, moveintogroup, l
    bind = SUPER CTRL, right, moveintogroup, r
    bind = SUPER CTRL, up, moveintogroup, u
    bind = SUPER CTRL, down, moveintogroup, d
    
    # Restore Strict Workspace Rules
    windowrulev2 = workspace 1, class:^(google-chrome|firefox)$
    windowrulev2 = group set, class:^(google-chrome|firefox)$
    
    windowrulev2 = workspace 2, class:^(code|jetbrains-idea|codeblocks)$
    windowrulev2 = group set, class:^(code|jetbrains-idea|codeblocks)$
    
    windowrulev2 = workspace 3, class:^(kitty)$
    windowrulev2 = group set, class:^(kitty)$
    
    windowrulev2 = workspace 4, class:^(discord|org\.telegram\.desktop|com\.ktechpit\.whatsie|Spotify)$
    windowrulev2 = group set, class:^(discord|org\.telegram\.desktop|com\.ktechpit\.whatsie|Spotify)$
