general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 1800                                # 30 mins
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

# The screen-off block is completely removed to keep your lock screen lit!

listener {
    timeout = 10800                               # 3 hours
    on-timeout = systemctl suspend                # suspend pc
}

# --- Taskwarrior Smart AFK Tracking ---
listener {
    timeout = 300                                 # 5 minutes of AFK
    on-timeout = ~/.scripts/task-auto-pause.sh    # Run the pause script
    on-resume = ~/.scripts/task-auto-resume.sh    # Run the math script when back
}
